### ISSUE TITLE
Provide website link in readme.md

### ISSUE THREAD

**Issue by amritregmi26** [Kamran1819G/Algopedia#23]
I wanted to view my contribution on the website. Since it has a website folder, I assume that there exists a website. But I can't find a website link to view my contribution.

**Comment by Kamran1819G** [comment]
The website link is conveniently located in the right sidebar of the repository. You can review the website by navigating to the following URL: [Algopedia](https://algopedia.vercel.app/). It's important to note that your contributions will not be visible until they are merged into the main codebase. However, rest assured that I will provide support for temporary websites in pull requests as well in the near future.

**Comment by amritregmi26** [comment]
Okay I can see it now!!! Thanks.
