### ISSUE TITLE
Can we add leetcode's problems' solutions inside a new folder? 

### ISSUE THREAD

**Issue by amritregmi26** [Kamran1819G/Algopedia#27]
path: /Algorithms/LeetCode
folderStructure: /LeetCode/QuestionNo1/ (question_name.js + question_name.py + question_name.cpp)

**Comment by Kamran1819G** [comment]
Thank you for the suggestion to organize LeetCode solutions. It sounds like a great idea, and I appreciate your input. However, at this time, I'd like to keep things as they are. We can definitely revisit this idea in the future, and I'll keep it in mind for Algopedia. Your input is valuable, and I'm open to making improvements down the road. Thank you for understanding.

**Comment by amritregmi26** [comment]
can we add the easy level leetcode's problem inside the programs folder? or what are you supposed to add there? can it be any program?

**Comment by Kamran1819G** [comment]
That folder is dedicated to programs like Factorial, Hello World, and Two Sum Program, So you can add leetcode questions but you have to frame that questions into simple programs

**Comment by amritregmi26** [comment]
Ok Thanks @Kamran1819G
