### ISSUE TITLE
Documentation duplication

### ISSUE THREAD

**Issue by rajivaPavan** [Kamran1819G/Algopedia#7]
Since there already is documentation on how to contribute to the repository in the `CONTRIBUTING.md` file, isn't it better just to add a link to it in the `README.md` file instead of writing it all over again? 🤔

**Comment by Kamran1819G** [comment]
Thanks for Suggesting, Please create PR for that.

**Comment by Kamran1819G** [comment]
Thanks for suggesting, Please create PR for that and please check documentation again for any typo error.
